export const GET_PROD_LIST = 'GET_PROD_LIST';
export const GET_PROD_LIST_START = 'GET_PROD_LIST_START';
export const GET_PROD_LIST_SUCCESS = 'GET_PROD_LIST_SUCCESS';
export const GET_PROD_LIST_ERROR = 'GET_PROD_LIST_ERROR';

export const UPDATE_PROD_DATA = 'UPDATE_PROD_DATA';

export const GET_GRAND_TOTAL = 'GET_GRAND_TOTAL';